;;; exploratory-pkgs-conf.el --- Exploratory Packages Configuration  -*- lexical-binding: t; -*-
;; This file is auto generated by Emacs.org

;; Author: Erik Almaraz <erik@almarazlabs.com>
;; Maintainer: Erik Almaraz <erik@almarazlabs.com>
;; Created 2021-12-05 Sun
;; Version: 0.1
;; Keywords: Emacs, .emacs, init, Emacs Lisp
;; URL: https;//github.com/skribest/emacs-config

;;; Commentary

;; Introduction (TBD)


;;; References:

;;   [1] 
;;   [2] 
;;   [3] 

;;<=================================================================================================>

;;; Chemtable & chembalance
(use-package chemtable
  :init
  (require 'chemtable)
  ;;:config
  )

(use-package chembalance
  :init
  (require 'chembalance)
  ;;:config
  ;;(chembalance-arrow-syntax (list of accepted arrows))
  ;;(chembalance-insert-string 1) ;if non-nil, when you call chembalance with selected region,
  ;;chembalance will kill that region and insert the balanced reaction.
  )

;;; EWW Configuration (native to Emacs), hence set `straight' to `nil'.
(use-package eww
  :straight nil
  :config
  ;; make Emacs always use its own browser for opening URL links
  (setq browse-url-browser-function 'eww-browse-url))

;;; Open URL in new buffer
;; Thanks to Xah Emacs (http://xahlee.info/emacs/emacs/emacs_eww_web_browser.html)
;; for the following code contribution.
;; Eww was written by Lar Magne Ingebrigtsen (http://quimby.gnus.org/lmi/lmi.html)
;; see his blog (http://lars.ingebrigtsen.no/2013/06/16/eww/) for more information.

(when (fboundp 'eww)
  (defun ri/rename-eww-buffer ()
    "Rename `eww-mode' buffer so sites open in new page."
    (let (($title (plist-get eww-data :title)))
      (when (eq major-mode 'eww-mode )
        (if $title
            (rename-buffer (concat "eww " $title ) t)
          (rename-buffer "eww" t)))))

  (add-hook 'eww-after-render-hook 'ri/rename-eww-buffer))

;;;Footer


;;; exploratory-packages-conf.el ends here
