;;; roam-conf.el --- Emacs Org Roam Configuration  -*- lexical-binding: t; -*-
;; This file is auto generated by Emacs.org

;; Author: Erik Almaraz <erik@almarazlabs.com>
;; Maintainer: Erik Almaraz <erik@almarazlabs.com>
;; Created 2021-12-05 Sun
;; Version: 0.1
;; Keywords: Emacs, .emacs, init, Emacs Lisp
;; URL: https;//github.com/skribest/dotEmacs

;;; Commentary

;;; References:

;;   [1] 
;;   [2] 
;;   [3] 

;;<=================================================================================================>


;;; Code:

;;; Initialize Org Roam
(use-package org-roam
  ;;:demand t ; This is significantly slowing my startup performance, but is needed for hacks!
  :after org
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory def/org-roam-dir)
  (org-roam-completion-everywhere t)
  (org-roam-completion-system 'default)
  (org-roam-capture-templates
   '(("d" "default" plain
      "%?"
      :if-new
      (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                 "#+title: ${title}\n#+category: ${title}\n#+filetags: Default")
      :unnarrowed t)
     ("p" "project" plain
      ;;"* Goals\n\n%?\n\n* Tasks\n\n** TODO Add initial tasks\n\n* Dates\n\n"
      (file "~/.emacs.d/OrgFiles/Roam/Templates/ProjectTemplate.org")
      :if-new
      (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                 "#+title: ${title}\n#+category: ${title}\n#+filetags: Project")
      :unnarrowed t)
     ;; This template is still under development
     ("s" "sample requests" table-line
      ;; This org file template give a "bad template" error after capture is complete...
      ;;(file "~/.emacs.d/OrgFiles/Roam/Templates/SampleRequests.org")
      "| %U | %^{PDR#} | %^{Trade Name} | %^{Supplier} | %^{Notes} | %? |"
      :if-new
      (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                 "#+title: ${title}\n#+category: ${title}\n#+filetags: Sample Requests")
      :unnarrowed t
      :kill-buffer t)
     ))
  (org-roam-dailies-directory "Journal/")
  (org-roam-dailies-capture-templates
   '(("d" "default" entry
      "* %<%I:%M %p>: %?"
      :if-new
      (file+head "%<%Y-%m-%d-%a>.org" "#+title: %<%Y-%m-%d-%a>\n"))))
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert)
         ;;("C-c n I" . org-roam-node-insert-immediate)
         ;; ("C-c n p" . my/org-roam-find-project)
         ;; ("C-c n b" . my/org-roam-capture-inbox)
         ;; ("C-c n t" . my/org-roam-capture-task)
         :map org-mode-map
         ("C-M-i" . completion-at-point)
         :map org-roam-dailies-map
         ("Y" . org-roam-dailies-capture-yesterday)
         ("T" . org-roam-dailies-capture-tomorrow)
         )
  :bind-keymap
  ("C-c n d" . org-roam-dailies-map)

  ;; Key binding for sample request entries
  ;;("C-c s r" . (lambda () (interactive) (org-capture nil "s"))) 
  :config
  (require 'org-roam-dailies) ;; Ensure the keymap is available
  (org-roam-setup) ;; Not exactly sure what this does or why I initially used this...
  (org-roam-db-autosync-mode))

;;; Footer

;; roam-conf.el ends here
